### ISSUE TITLE
Messages app launched

### ISSUE THREAD

**Issue by a-dekker** [R1tschY/harbour-sailfishconnect#10]
At startup, the messages app is also launched and directly closed. Any reason for this behavior?

**Comment by R1tschY** [comment]
Could you please explain your setup (Sailfish Connect version, SailfishOS version, self-compiled?, Emulator?) and the steps to reproduce this.

**Comment by a-dekker** [comment]
**Sailfish Connect version**: harbour-sailfishconnect-0.1-1.armv7hl (openrepos)
**SailfishOS version**: Sailfish OS 2.2.0.29 (Mouhijoki)
**Device**: Xperia X

I thought this would be a general issue, but apparently not. After starting Sailfish Connect, the message app tile shows up next to the Sailfish Connect tile itself, but disappears after about 5 seconds (as it get terminated I presume).

**Comment by a-dekker** [comment]
Disabling the "Send SMS" plugin prevents the behavior.
