### ISSUE TITLE
Terminating Sailfish Connect

### ISSUE THREAD

**Issue by a-dekker** [R1tschY/harbour-sailfishconnect#11]
Closing Sailfish Connect means it keeps running in the background. Most of the time that whats you want. But there is no other way then killing the background processes to stop it as far as I can tell. Perhaps an "exit" option in the menu could accomplish a real exit?

**Comment by R1tschY** [comment]
Thank you for your feedback.

In version 0.2 there will be an option to disable this behavior. The default will be to not run in background. I think it is the better default.

I will try to add the button for the 0.2 release.
