### ISSUE TITLE
Sending SMS: Messages App must be open

### ISSUE THREAD

**Issue by R1tschY** [R1tschY/harbour-sailfishconnect#12]
Sending a SMS is only possible when the SailfishOS Messages app is running.

**Comment by sbridger** [comment]
Halftux made a command line sender for me: SMSRUN
http://talk.maemo.org/showpost.php?p=1560913&postcount=442

for what it might be worth....

**Comment by R1tschY** [comment]
SMS feature will be rewritten to send SMS directly
