### ISSUE TITLE
No commands available on KDE

### ISSUE THREAD

**Issue by blizzz** [R1tschY/harbour-sailfishconnect#26]
When my XA2 and KDE Plasma are connected, no commands are available on the KDE Connect plugin. It stays empty, but for the battery state:

![Screenshot_20190819_100132](https://user-images.githubusercontent.com/2184312/63248750-53cf6980-c268-11e9-8409-ab8deac2204a.png)

Runing `kdeconnect-cli  -d {ID} --list-commands` yields an empty output (exit code 0). 

However, sharing clipboard and receiving notifications from the phone (as well as touchpad control  from the phone) are working, for instance. Also running `kdeconnect-cli  -d {ID} --send-sms "test" --destination "{PHONENO}"` opens the SMS dialog. 

I am running Sailfish Connect 0.4-2 and kdeconnect 1.3.5-1 (on KDE Plasma 5.16.4-1)

**Comment by R1tschY** [comment]
The commands plugin is not yet implemented by Sailfish Connect. So `--list-commands` will show nothing until someone implements it. I don't use Plasma so I don't known what should be shown in the window other than the battery state.

**Comment by blizzz** [comment]
Ok about `--list-commands?`, i had wrong expectations than.

@R1tschY Then, you're on Gnome? According the the [screenshot of GSConnect](https://extensions.gnome.org/extension-data/screenshots/screenshot_1319_1NByhZ8.png)  you would have some options to interact with the device. To compare it with that.

On KDE Plasma, at least according to [Suse's screenshot](https://software.opensuse.org/images/thumbnails/kdeconnect-kde.png), there used to be a list of notifications, but it might be they just went to the notification widget, but i has some buttons etc. What I was looking for was a way to send (or reply to) SMS. And I believe I saw this once upon a time, but maybe I am mixing up something. Maybe it's alright, but the huge amount of whitespace is irritating and suggesting there should be something else. Perhaps it's a KDE Connect paper cut on KDE after all.

**Comment by R1tschY** [comment]
In GSConnect, but also with KDEConnect, the file browser integration works. But most other things that can be seen in the screenshot are not working yet. For SMS support the contact plugin is missing. For file browsing is SFTP plugin missing. For ringing is FindMyPhone missing. Notifications should somehow work, but must be activated in the plugins list of the device in Sailfish Connect.

Like you can see in the README many plugins are missing. So contributions are welcome! :wink:
