### ISSUE TITLE
Trailing \n in deviceId causes "...strange ssl certificate" error while pairing

### ISSUE THREAD

**Issue by slashdotted** [R1tschY/harbour-sailfishconnect#28]
I'm trying to use SailfishConnect with GSConnect, but pairing fails due to a trailing \n in the deviceId. 

This results in an error _"[W] Device::Device(QObject*, KdeConnectConfig*, const QString&, const QString&, const QString&)::<lambda:111 - Device pairing error "This device cannot be paired because it sends a strange ssl certificate."_. 

I didn't investigate the issue so much, so I don't really know if it's GSConnect that sends the id string with a trailing newline or if it's sailfish connect that adds it somehow. 

To quickly solve the issue I've changed the sanitizeDeviceId method in device.cpp to trim the deviceId before replacing non alphanumerical characters.

**Comment by slashdotted** [comment]
Simple patch to trim the deviceID
[trim_deviceid.zip](https://github.com/R1tschY/harbour-sailfishconnect/files/3689997/trim_deviceid.zip)

**Comment by andyholmes** [comment]
Yep, definitely our bug in GSConnect. Should be fixed in v27-rc1 so it's your call if you want to leave the line trimming in your next release :)

**Comment by R1tschY** [comment]
Okay, then it does not make sense to fix it in SailfishConnect.
