### ISSUE TITLE
Add a link to your port in GSConnect?

### ISSUE THREAD

**Issue by andyholmes** [R1tschY/harbour-sailfishconnect#29]
Hi, I had forgotten their was more than one SailfishOS port for KDE Connect. Currently, we have a link in GSConnect's settings dialog pointing to Adam Piggz' client.

Would like us to add a link to your port in v27 (soon) as well? If so, where is the best URL to point to for end-users?

**Comment by R1tschY** [comment]
Sounds great :+1: especially since Adam Piggz is not working anymore on the Sailfish port of KDE Connect. You can link to https://openrepos.net/content/r1tschy/sailfish-connect which is the best place to download SailfishConnect.

**Comment by andyholmes** [comment]
Oh, good to know! I've just replaced Adam's link with yours then :)
