### ISSUE TITLE
can't sync sms with GSConnect

### ISSUE THREAD

**Issue by vbelloir** [R1tschY/harbour-sailfishconnect#31]
Desktop
Ubuntu 18.04.3 with Gnome 3.28.2 and GSconnect installed
Xperia XA2 with SFOS 3.2.0.12 with Sailfish Connect 0.4.1.1.

Devices are paired, I can share clipboard, touchapd, send files...

But Desktop message app stays empty
![image](https://user-images.githubusercontent.com/13942805/69577245-4398fa00-0fce-11ea-9a0f-88b99491c751.png)

SMS plugin is enabled on Desktop side
![image](https://user-images.githubusercontent.com/13942805/69577351-7511c580-0fce-11ea-888d-2872773d0883.png)

And on phone side
![image](https://user-images.githubusercontent.com/13942805/69577458-a7232780-0fce-11ea-8b37-92957b6dbc63.png)

Do I miss something?

**Comment by tanghus** [comment]
On Monday, 25 November 2019 21.58 vbelloir wrote:
> Do I miss something?

I believe it's not yet implemented in sailfishconnect.

-- 

/Thomas

**Comment by vbelloir** [comment]
This was also what I believed, but, in the [README page](https://github.com/R1tschY/harbour-sailfishconnect) we can see.
![image](https://user-images.githubusercontent.com/13942805/69610096-686f8a80-102b-11ea-9cea-980d45669e83.png)

**Comment by R1tschY** [comment]
Reading SMS history is not implemented yet. Reading contacts will be part of the next release. Yet without the list of contacts you can't send SMS in GSConnect.

**Comment by vbelloir** [comment]
Ok, I understand that it is not yet available, but README page should be updated.
