### ISSUE TITLE
Testing with Win10 KDEConnect

### ISSUE THREAD

**Issue by sbridger** [R1tschY/harbour-sailfishconnect#33]
Just thought I would report on trying V0.5-1 with
kdeconnect-kde-master-268-windows-msvc2017_64-cl.exe

On Win10: Firewall was blocking kdeconnectd. Type "firewall" to check if kdeconnectd is blocked. but issue was my wifi type was public, and blocked for public. 

kdeconnect-app.exe doesn't show a window (is it supposed to?) all interaction is through the kedconnect tray icon (hidden by default)

- clipboard working both ways
- battery level showing
- touchpad working to control pc, left/right mouse buttons work
- keyboard to pc mostly works. comma, space and fullstop don't work (same on linux)
- keyboard from pc to sfos : "Remote keyboard from the desktop" plugin is not listed in the KDE Connect settings. Is this Windows end or SFOS end issue?
- media player > button starts/stops youtube
- send pings works both ways
- send sms : endless waiting circle, not working. Same if messages is foreground in SFOS
- file send from SFOS: silently saved to Downloads folder
- file send from PC: Can select file. silently saved to /home/nemo/Downloads/
- inhibit screensaver: doesn't work
- sfos notification to PC: doesn't work
- contacts sync: Nothing appears to happen when I create new person in People app on PC or People app on SFOS

Summary: 
The two main functions I want: Use PC keyboard -> phone and SMS from PC not working yet.
File sends are silent with no ack, so you don't know they happened. Should notify or something.

**Comment by R1tschY** [comment]
For issues against the Windows port of KDE Connect please use: https://invent.kde.org/kde/kdeconnect-kde/issues
At the moment it is experimental as I now.

- "Remote keyboard from the desktop" is not supported for Sailfish Connect. A virtual keyboard for Sailfish OS is needed. Use clipboard plugin as workaround.
- SMS sending is currently buggy. In the (far) future the SMS will be send without the Messages app.
- Notifications for Download/Uploads will be in next release
- "inhibit screensaver" must be a KDE Connect issue
- "sfos notification to PC" works in Linux, also a KDE Connect issue
- "contacts sync" is in KDE Connect only used for SMS app as I now
