### ISSUE TITLE
[Feature request] Manually add a peer device

### ISSUE THREAD

**Issue by AP41000** [R1tschY/harbour-sailfishconnect#35]
The Android _KDE connect_ app allows you to manually add a device when peer auto-detection is unable to reach the intended peer. It happens if you have to go across a router to reach it. This feature would nicely complete Sailfish connect.

**Comment by R1tschY** [comment]
The feature has been planned for a long time. But it wasn't implemented until now. It is maybe a work-around for #17. Let's hope I will soon have enough time to implement it. 

See also: https://invent.kde.org/kde/kdeconnect-kde/merge_requests/141 (Sailfish Connect will soon use KDE Connect as backend)

**Comment by R1tschY** [comment]
Fixed with https://github.com/R1tschY/harbour-sailfishconnect/commit/0288383375eba5a97ec4dc6626e6714e9f5a004b
