### ISSUE TITLE
Text won't send with gsconnect

### ISSUE THREAD

**Issue by BATHTUBISREAL** [R1tschY/harbour-sailfishconnect#36]
When I try to send an sms text on my computer, the messenger app implies that the text has been sent. When I look at my phone, the sms has not been sent but it is typed into my phone text keyboard.

**Comment by R1tschY** [comment]
At the moment the behavior is not optimal. The text for the SMS is just given to the Messages app as a draft and not send. So the SMS content can be checked and the system recognizes the than send SMS correctly. In a future version this hopefully change and the SMS is send directly.
