### ISSUE TITLE
No notifications in KDE Connect

### ISSUE THREAD

**Issue by birefringence** [R1tschY/harbour-sailfishconnect#37]
I have installed KDE Connect v1.3.3 and Sailfish Connect v0.5.1 on Sailfish OS v3.2.1.20 (Sony Xperia X). Connecting works fine, but notifications from the mobile are not shown on the desktop. All other features I have tested so far seem to work.

**Comment by R1tschY** [comment]
I'm using KDE Connect 1.3.5 and I see notifications. Are you sure you enabled the notifications plugin? It is deactivated by default. 

Can you name what notifications you can't see? I use F-Droid package source update notifications for testing.

**Comment by birefringence** [comment]
Yes, I have enabled the notifications plugin in the Sailfish Connect settings. I have also checked that the Receive Notifications plugin is active on the PC. I have tried different types of notifications (SMS, E-Mail and now also the F-Droid source update) and none appear. Maybe I should try to upgrade KDE Connect. I'm currently using the version that comes with openSUSE Leap 15.1.

**Comment by birefringence** [comment]
Ok, I've upgraded to v1.3.5 from openSUSE build services but it is still not working. Is there any way to look at any logs for error messages?

**Comment by R1tschY** [comment]
Do you have the Developer Mode enabled? Then you can call SailfishConnect from the Terminal:

    [nemo@Sailfish ~]$ harhour-sailfishconnect

The log messages will then printed (but only warnings and errors). For debug messages you need a debug build, which I can provide, when needed.

**Comment by birefringence** [comment]
Ok, I would try the debug build then. With the normal version the log messages do not contain anything interesting (there is no error or anything suspicious).

**Comment by R1tschY** [comment]
Here a current debug build of 0.6:

https://send.firefox.com/download/72c9ce51cf8065a9/#tWzJqKD8dzAsQtMdQlS5kA

The debug messages are very verbose, so check for private information before posting the log.

**Comment by birefringence** [comment]
Thanks! This version works as expected and notifications are transmitted :-) There is no error message. Do you want to see the log anyway?

**Comment by R1tschY** [comment]
I looked at the differences to the 0.5-1 version and there is hardly one. Can you please check with this 0.5-1 debug build:
https://send.firefox.com/download/eb0b56d9783d5cb8/#gIaDORM0y0LHRCwO4a2wkA
I just want to understand what the problem was.

**Comment by birefringence** [comment]
This seems to be exactly the same file as you sent previously (I checked the hash value). So the debug build seems to work, but the normal one doesn't (I went back to the version from OpenRepos to double check).

**Comment by R1tschY** [comment]
I fixed the problem. Only the release build had the issue. So I was pretty confused until I found the bug.

**Comment by birefringence** [comment]
Forgot to say thank you :-) Works great now!
