### ISSUE TITLE
Dependency issue with SFOS 4.0

### ISSUE THREAD

**Issue by Karry** [R1tschY/harbour-sailfishconnect#42]
Hi. Today was release Sailfish 4.0.1 (Koli). Sailfish connect cannot be installed anymore. It fails with unsatisfied dependency:
```
Problem: nothing provides libcontextkit-statefs-qt5.so needed by harbour-sailfishconnect-0.5.1-1.armv7hl
```

**Comment by R1tschY** [comment]
Thanks for reporting. The fix will be released with 0.6 (hopefully this weekend). Was already fixed in https://github.com/R1tschY/harbour-sailfishconnect/commit/16352c671b66dc61b56862bd9ac129c46b794e76.
