### ISSUE TITLE
Please provide aarch64 package

### ISSUE THREAD

**Issue by Karry** [R1tschY/harbour-sailfishconnect#46]
Hi.

Jolla released full SFOS for Xperia 10.II yesterday. On this device just aarch64 applications may be used. It would be great to provide aarch64 build of Sailfish Connect in store/openrepos.

**Comment by fridlmue** [comment]
@R1tschY can we provide help to deploy a aarch64 package?

**Comment by Karry** [comment]
I tried to build it for aarch64, but it is downloading dependencies by Conan, and they are not available for aarch64 yet. I have just a little experience with Conan, so I give up it for now...

**Comment by Mazhoon** [comment]
> I tried to build it for aarch64, but it is downloading dependencies by Conan, and they are not available for aarch64 yet. I have just a little experience with Conan, so I give up it for now...

I tried also building it, I interpreted that Conan binaries based on recipes at https://github.com/R1tschY/sailfishos-conan fail to get downloaded, since the external repository has since shut down. (I didn't manage to find out yet how to build and supply the conan packages locally to the build process, it seems to be possible, but didn't find a straightforward guide, and have neither any experience with the tool)

**Comment by R1tschY** [comment]
I'm sorry, I've been very busy the last few weeks.

The Conan binary packages were hosted on Bintray. Bintray was shut down on 1st of May. I had not the time to migrate to a GitLab conan repository.

But it should be possible to build the conan packages into the local repository with `conan export-pkg`. But I didn't tried to yet.

**Comment by R1tschY** [comment]
I have invested some time:
* Packages are here (without binaries for now): https://gitlab.com/R1tschY/sailfishos-conan/-/packages
* aarch64 is included in CI: https://github.com/R1tschY/harbour-sailfishconnect/actions

**Comment by fridlmue** [comment]
Thank you, @R1tschY !
KDE Connect with Sailfish Connect has become so much of a beloved feature, that I can't call my phone a "daily driver" without it...

**Comment by Karry** [comment]
Thank you!
