### ISSUE TITLE
Sailfish-connect does not start in Rauma 4.4.0.58

### ISSUE THREAD

**Issue by rigow** [R1tschY/harbour-sailfishconnect#48]
Haven't tried to re-install yet. Starting the application, it gives some startup screen as an application tile in the app-list, but then the screen goes away again. I haven't found the binary to start from commandline to see what is happening.

**Comment by rigow** [comment]
https://forum.sailfishos.org/t/sailfish-connect-does-not-start-anymore/10736/
It fails because of SailJail. If you start sailfish-connect (harbour-sailfishconnect) from terminal it works.
I can confirm that. So how to satisfy SailJail is the question.

**Comment by Karry** [comment]
It is solved in master branch by this commit (sandboxing is disabled): https://github.com/R1tschY/harbour-sailfishconnect/commit/363c3dd06bcbae33c9841124fce9ff1683c8b246 

@R1tschY do you plan to make new release anytime soon please?

**Comment by R1tschY** [comment]
Expect a bugfix release soon.
